steps:
- name: gcr.io/cloud-builders/bazel
  args:
  - build
  - //cmd/players
  - "--google_default_credentials"
  - "--remote_http_cache=https://storage.googleapis.com/${_BUCKET_NAME}"
  - "--verbose_failures"
  waitFor: ["-"]
  timeout: 1200s
timeout: 1200s
