type sessionServer struct {
	
}

func (s *sessionServer) GetFeature(ctx context.Context, point *pb.Point) (*pb.Feature, error) {
	...
}
...

func (s *sessionServer) ListFeatures(rect *pb.Rectangle, stream pb.RouteGuide_ListFeaturesServer) error {
	...
}
...

func (s *sessionServer) RecordRoute(stream pb.RouteGuide_RecordRouteServer) error {
	...
}
...

func (s *sessionServer) RouteChat(stream pb.RouteGuide_RouteChatServer) error {
	...
}